#!/bin/bash
#SCRIPT:  stop_ciel_local.sh
#PURPOSE: Stop ciel locally

FILENAME_MASTER=$1
FILENAME_WORKERS=$2
USERNAME=root

CIEL_DIR=~/zubair/ciel_data

while read MASTER
do
      echo $PID
      PID=`cat $CIEL_DIR/$MASTER/pid/$MASTER`
      echo "Stopping CIEL master on $MASTER"
      kill $PID
      sleep 1

done < $FILENAME_MASTER

while read MACHINE
do
      PID=`cat $CIEL_DIR/$MACHINE/pid/$MACHINE`
      echo "Stopping CIEL worker on $MACHINE"
      kill $PID
      sleep 1

done < $FILENAME_WORKERS

