#!/bin/bash
#SCRIPT:  start_ciel_local.sh
#PURPOSE: Start ciel locally

FILENAME_MASTER=$1
FILENAME_WORKERS=$2
FILENAME_WORKERS2=$3
USERNAME=root

CIEL_DIR=~/zubair/ciel_data
BS_DIR=$CIEL_DIR/block_store
JJ_DIR=$CIEL_DIR/job_journal

MASTER_PORT=8000
WORKER_PORT=54000
WORKER_PORT2=50000
NUM_THREADS=1

while read MASTER
do
      echo "Starting CIEL master on $MASTER"
      ciel master --daemonise --logfile="/root/zubair/$MASTER.log"
      sleep 1

done < $FILENAME_MASTER

while read MACHINE
do
      echo "Starting CIEL worker on $MACHINE"
      ciel worker --master="http://localhost:$MASTER_PORT" --port=$WORKER_PORT --daemonise --logfile="/root/zubair/$MACHINE.log"
      let "WORKER_PORT += 1"
      sleep 1

done < $FILENAME_WORKERS

while read MACHINE2
do
      echo "Starting CIEL worker on $MACHINE2"
      ciel worker --master="http://localhost:$MASTER_PORT" --port=$WORKER_PORT2 --daemonise --logfile="/root/zubair/$MACHINE.log"
      let "WORKER_PORT2 += 1"
      sleep 1

done < $FILENAME_WORKERS2
